const dummymatch = {
    groundinfo: {
        groundpayload: {
            groundid: "-1",
            img: "",
            location: "",
            name: "",
            parking: "",
            shower: "",
            toilet: "",
        },
    },
    usersinfo: {
        userinfo: [
            {
                admin: false,
                createdAt: "",
                fullname: "",
                gender: "",
                password: "",
                penalty: 0,
                phonenum: "",
                position: "",
                preferredloca: null,
                preferredtime: null,
                totalAssist: 0,
                totalGoal: 0,
                totalMatch: 0,
                totalPoint: 0,
                totalShooting: 0,
                totalWin: 0,
                updatedAt: "",
                userid: "",
                winrate: "",
            },
            {
                admin: false,
                createdAt: "",
                fullname: "",
                gender: "",
                password: "",
                penalty: 0,
                phonenum: "",
                position: "",
                preferredloca: null,
                preferredtime: null,
                totalAssist: 0,
                totalGoal: 0,
                totalMatch: 0,
                totalPoint: 0,
                totalShooting: 0,
                totalWin: 0,
                updatedAt: "",
                userid: "",
                winrate: "",
            },
            {
                admin: false,
                createdAt: "",
                fullname: "",
                gender: "",
                password: "",
                penalty: 0,
                phonenum: "",
                position: "",
                preferredloca: null,
                preferredtime: null,
                totalAssist: 0,
                totalGoal: 0,
                totalMatch: 0,
                totalPoint: 0,
                totalShooting: 0,
                totalWin: 0,
                updatedAt: "",
                userid: "",
                winrate: "",
            },
            {
                admin: false,
                createdAt: "",
                fullname: "",
                gender: "",
                password: "",
                penalty: 0,
                phonenum: "",
                position: "",
                preferredloca: null,
                preferredtime: null,
                totalAssist: 0,
                totalGoal: 0,
                totalMatch: 0,
                totalPoint: 0,
                totalShooting: 0,
                totalWin: 0,
                updatedAt: "",
                userid: "",
                winrate: "",
            },
            {
                admin: false,
                createdAt: "",
                fullname: "",
                gender: "",
                password: "",
                penalty: 0,
                phonenum: "",
                position: "",
                preferredloca: null,
                preferredtime: null,
                totalAssist: 0,
                totalGoal: 0,
                totalMatch: 0,
                totalPoint: 0,
                totalShooting: 0,
                totalWin: 0,
                updatedAt: "",
                userid: "",
                winrate: "",
            },
            {
                admin: false,
                createdAt: "",
                fullname: "",
                gender: "",
                password: "",
                penalty: 0,
                phonenum: "",
                position: "",
                preferredloca: null,
                preferredtime: null,
                totalAssist: 0,
                totalGoal: 0,
                totalMatch: 0,
                totalPoint: 0,
                totalShooting: 0,
                totalWin: 0,
                updatedAt: "",
                userid: "",
                winrate: "",
            },
            {
                admin: false,
                createdAt: "",
                fullname: "",
                gender: "",
                password: "",
                penalty: 0,
                phonenum: "",
                position: "",
                preferredloca: null,
                preferredtime: null,
                totalAssist: 0,
                totalGoal: 0,
                totalMatch: 0,
                totalPoint: 0,
                totalShooting: 0,
                totalWin: 0,
                updatedAt: "",
                userid: "",
                winrate: "",
            },
            {
                admin: false,
                createdAt: "",
                fullname: "",
                gender: "",
                password: "",
                penalty: 0,
                phonenum: "",
                position: "",
                preferredloca: null,
                preferredtime: null,
                totalAssist: 0,
                totalGoal: 0,
                totalMatch: 0,
                totalPoint: 0,
                totalShooting: 0,
                totalWin: 0,
                updatedAt: "",
                userid: "",
                winrate: "",
            },
            {
                admin: false,
                createdAt: "",
                fullname: "",
                gender: "",
                password: "",
                penalty: 0,
                phonenum: "",
                position: "",
                preferredloca: null,
                preferredtime: null,
                totalAssist: 0,
                totalGoal: 0,
                totalMatch: 0,
                totalPoint: 0,
                totalShooting: 0,
                totalWin: 0,
                updatedAt: "",
                userid: "",
                winrate: "",
            },
            {
                admin: false,
                createdAt: "",
                fullname: "",
                gender: "",
                password: "",
                penalty: 0,
                phonenum: "",
                position: "",
                preferredloca: null,
                preferredtime: null,
                totalAssist: 0,
                totalGoal: 0,
                totalMatch: 0,
                totalPoint: 0,
                totalShooting: 0,
                totalWin: 0,
                updatedAt: "",
                userid: "",
                winrate: "",
            },
            {
                admin: false,
                createdAt: "",
                fullname: "",
                gender: "",
                password: "",
                penalty: 0,
                phonenum: "",
                position: "",
                preferredloca: null,
                preferredtime: null,
                totalAssist: 0,
                totalGoal: 0,
                totalMatch: 0,
                totalPoint: 0,
                totalShooting: 0,
                totalWin: 0,
                updatedAt: "",
                userid: "",
                winrate: "",
            },
            {
                admin: false,
                createdAt: "",
                fullname: "",
                gender: "",
                password: "",
                penalty: 0,
                phonenum: "",
                position: "",
                preferredloca: null,
                preferredtime: null,
                totalAssist: 0,
                totalGoal: 0,
                totalMatch: 0,
                totalPoint: 0,
                totalShooting: 0,
                totalWin: 0,
                updatedAt: "",
                userid: "",
                winrate: "",
            },
            {
                admin: false,
                createdAt: "",
                fullname: "",
                gender: "",
                password: "",
                penalty: 0,
                phonenum: "",
                position: "",
                preferredloca: null,
                preferredtime: null,
                totalAssist: 0,
                totalGoal: 0,
                totalMatch: 0,
                totalPoint: 0,
                totalShooting: 0,
                totalWin: 0,
                updatedAt: "",
                userid: "",
                winrate: "",
            },
        ],
    },
};

export default dummymatch;
